# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Monster'
description: "Jekyll Theme"

# Authors's info
authors:
  rodin:
    name: Rodin Luo
    display_name: Rodin
    nickname: Rodin
    bio: 'I am Rodin...'
    email: 
    twitter:
    github: 
    location: 'Chengdu, China'
    url: http://www.mocoven.com
    image: 'assets/images/rodin.png'
    short_url: 'mocoven.com'
  wei:
    name: 默考文 Wei
    display_name: 默考文 Wei
    nickname: Wei
    bio: 'I am Mocoven.'
    email: mocovenwitch@gmail.com
    twitter: mocoven
    github: mocovenwitch
    location: 'Sydney, Australia'
    url: http://www.mocoven.com
    image: 'assets/images/rodin.png'
    short_url: 'mocoven.com'

# Tags
mytags: [talk, android]


google_analytics: 
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]
